"""NarratorDB: local-first, durable memory for AI systems."""

from .config import (
    CapturePolicy,
    CompilerConfig,
    CompilerKind,
    ConfigurationError,
    ConfigurationRequiredError,
    DEFAULT_OPENAI_MODEL,
    DEFAULT_OPENROUTER_MODEL,
    FeatureUnavailableError,
    MemoryMode,
    ModeConflictError,
    ProjectConfig,
    default_data_dir,
    default_db_path,
)
from .compiler import (
    CompileResult,
    CompileSessionInput,
    CompiledClaim,
    CompiledEntity,
    CompiledMemory,
    CompiledRelation,
    CompiledSummary,
    CompilerError,
    CompilerUsage,
    ContentFreeUsageLedger,
    EvidenceSpan,
    MemoryCompiler,
    ReferenceClaim,
    SourceMessage,
)
from .compiler_cache import CachedMemoryCompiler, CompiledSessionCache
from .database import (
    ArtifactRecallResult,
    ArtifactResult,
    CodeChunkRecallResult,
    CodeChunkResult,
    IngestResult,
    NarratorDB,
    RecallResult,
    RelationResult,
    SessionIngestResult,
)
from .engine import ENGINE_NAME, Engine
from .enrichment import BackgroundEnricher, EnrichmentRunner
from .intelligence import ContextBlock, ContextBundle, MemoryClaim

__all__ = [
    "ArtifactRecallResult",
    "ArtifactResult",
    "CodeChunkRecallResult",
    "CodeChunkResult",
    "CompileResult",
    "CompileSessionInput",
    "CompiledClaim",
    "CompiledEntity",
    "CompiledMemory",
    "CompiledRelation",
    "CompiledSessionCache",
    "CompiledSummary",
    "CompilerConfig",
    "CompilerError",
    "CompilerKind",
    "CompilerUsage",
    "ConfigurationError",
    "ConfigurationRequiredError",
    "ContextBlock",
    "ContextBundle",
    "ContentFreeUsageLedger",
    "DEFAULT_OPENAI_MODEL",
    "DEFAULT_OPENROUTER_MODEL",
    "ENGINE_NAME",
    "Engine",
    "EnrichmentRunner",
    "EvidenceSpan",
    "FeatureUnavailableError",
    "IngestResult",
    "MemoryMode",
    "MemoryClaim",
    "MemoryCompiler",
    "ModeConflictError",
    "NarratorDB",
    "ProjectConfig",
    "RecallResult",
    "ReferenceClaim",
    "RelationResult",
    "SessionIngestResult",
    "SourceMessage",
    "BackgroundEnricher",
    "CachedMemoryCompiler",
    "CapturePolicy",
    "default_data_dir",
    "default_db_path",
]

__version__ = "2.2.0"
